export enum ROLES {
  USER = "USER",
  COMPANY_OWNER = "COMPANY_OWNER",
  COMPANY_STAFF = "COMPANY_STAFF",
  SUPER_ADMIN = "SUPER_ADMIN",
}

export enum ACCOUNT_TYPES {
  LIABILITY = "LIABILITY",
  REVENUE = "REVENUE",
  ASSET = "ASSET",
  LOSS = "LOSS",
  CAPITAL = "CAPITAL",
  DEPRECIATION = "DEPRECIATION",
}
